In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter
%matplotlib inline
from sklearn.preprocessing import LabelEncoder

In [2]:
telcochurn=pd.read_csv("D:/Telecom Churn Data SingTel.csv")

In [3]:
telcochurn.head()

,State,Account Length,Area Code,Phone Number,International Plan,Voice mail Plan,Num of Voice mail Messages,Total Day Minutes,Total Day Calls,Total day Charge,...,Total Eve Calls,Total Eve Charge,Total Night Minutes,Total Night Calls,Total Night Charge,Total International Minutes,Total Intl Calls,Total Intl Charge,Number Customer Service calls,Churn
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

In [4]:
telcochurn.tail()

,State,Account Length,Area Code,Phone Number,International Plan,Voice mail Plan,Num of Voice mail Messages,Total Day Minutes,Total Day Calls,Total day Charge,...,Total Eve Calls,Total Eve Charge,Total Night Minutes,Total Night Calls,Total Night Charge,Total International Minutes,Total Intl Calls,Total Intl Charge,Number Customer Service calls,Churn
4995,HI,50,408,365-8751,no,yes,40,235.7,127,40.07,...,126,18.96,297.5,116,13.39,9.9,5,2.67,2,False.
4996,WV,152,415,334-9736,no,no,0,184.2,90,31.31,...,73,21.83,213.6,113,9.61,14.7,2,3.97,3,True.
4997,DC,61,415,333-6861,no,no,0,140.6,89,23.90,...,128,14.69,212.4,97,9.56,13.6,4,3.67,1,False.
4998,DC,109,510,394-2206,no,no,0,188.8,67,32.10,...,92,14.59,224.4,89,10.10,8.5,6,2.30,0,False.
4999,VT,86,415,373-8058,no,yes,34,129.4,102,22.00,...,104,22.70,154.8,100,6.97,9.3,16,2.51,0,False.

In [5]:
telcochurn.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Account Length,5000.0,100.258600,39.694560,1.0,73.000,100.00,127.00,243.00
Area Code,5000.0,436.911400,42.209182,408.0,408.000,415.00,415.00,510.00
Num of Voice mail Messages,5000.0,7.755200,13.546393,0.0,0.000,0.00,17.00,52.00
Total Day Minutes,5000.0,180.288900,53.894699,0.0,143.700,180.10,216.20,351.50
Total Day Calls,5000.0,100.029400,19.831197,0.0,87.000,100.00,113.00,165.00
Total day Charge,5000.0,30.649668,9.162069,0.0,24.430,30.62,36.75,59.76
Total Eve Minutes,5000.0,200.636560,50.551309,0.0,166.375,201.00,234.10,363.70
Total Eve Calls,5000.0,100.191000,19.826496,0.0,87.000,100.00,114.00,170.00
Total Eve Charge,5000.0,17.054322,4.296843,0.0,14.140,17.09,19.90,30.91
Total Night Minutes,5000.0,200.391620,50.527789,0.0,166.900,200.40,234.70,395.00
Total Night Calls,5000.0,99.919200,19.958686,0.0,87.000,100.00,113.00,175.00
Total Night Charge,5000.0,9.017732,2.273763,0.0,7.510,9.02,10.56,17.77
Total International Minutes,5000.0,10.261780,2.761396,0.0,8.500,10.30,12.00,20.00
Total Intl Calls,5000.0,4.435200,2.456788,0.0,3.000,4.00,6.00,20.00
Total Intl Charge,5000.0,2.771196,0.745514,0.0,2.300,2.78,3.24,5.40
Number Customer Service calls,5000.0,1.570400,1.306363,0.0,1.000,1.00,2.00,9.00

In [6]:
## If there are any True or False, Yes or No, T or F etc in your data you need to convert them to 0 & 1
## To do that you need to use np.where
le=LabelEncoder()

In [7]:
telcochurn["International Plan"]=le.fit_transform(telcochurn.iloc[:,4].values)

In [8]:
telcochurn["Voice mail Plan"]=le.fit_transform(telcochurn.iloc[:,5].values)

In [9]:
telcochurn.head()

,State,Account Length,Area Code,Phone Number,International Plan,Voice mail Plan,Num of Voice mail Messages,Total Day Minutes,Total Day Calls,Total day Charge,...,Total Eve Calls,Total Eve Charge,Total Night Minutes,Total Night Calls,Total Night Charge,Total International Minutes,Total Intl Calls,Total Intl Charge,Number Customer Service calls,Churn
0,KS,128,415,382-4657,0,1,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,0,1,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,0,0,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,1,0,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,1,0,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

In [10]:
telcochurn["Churn"]=le.fit_transform(telcochurn.iloc[:,20].values)

In [11]:
telcochurn.head()

,State,Account Length,Area Code,Phone Number,International Plan,Voice mail Plan,Num of Voice mail Messages,Total Day Minutes,Total Day Calls,Total day Charge,...,Total Eve Calls,Total Eve Charge,Total Night Minutes,Total Night Calls,Total Night Charge,Total International Minutes,Total Intl Calls,Total Intl Charge,Number Customer Service calls,Churn
0,KS,128,415,382-4657,0,1,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,0
1,OH,107,415,371-7191,0,1,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,0
2,NJ,137,415,358-1921,0,0,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,0
3,OH,84,408,375-9999,1,0,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,0
4,OK,75,415,330-6626,1,0,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,0

In [12]:
features=telcochurn.drop(['Churn','State','Area Code','Phone Number'],axis=1).columns

In [13]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
churnrf=RandomForestClassifier()

In [15]:
churnrf.fit(telcochurn[features],telcochurn["Churn"])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [16]:
churnrf.score(telcochurn[features],telcochurn['Churn'])

0.99460000000000004

In [17]:
predictions=churnrf.predict(telcochurn[features])

In [18]:
predictions

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [19]:
from sklearn import metrics

In [20]:
telcochurn["predictions"]=churnrf.predict(telcochurn[features])

In [21]:
telcochurn.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Account Length,5000.0,100.258600,39.694560,1.0,73.000,100.00,127.00,243.00
Area Code,5000.0,436.911400,42.209182,408.0,408.000,415.00,415.00,510.00
International Plan,5000.0,0.094600,0.292691,0.0,0.000,0.00,0.00,1.00
Voice mail Plan,5000.0,0.264600,0.441164,0.0,0.000,0.00,1.00,1.00
Num of Voice mail Messages,5000.0,7.755200,13.546393,0.0,0.000,0.00,17.00,52.00
Total Day Minutes,5000.0,180.288900,53.894699,0.0,143.700,180.10,216.20,351.50
Total Day Calls,5000.0,100.029400,19.831197,0.0,87.000,100.00,113.00,165.00
Total day Charge,5000.0,30.649668,9.162069,0.0,24.430,30.62,36.75,59.76
Total Eve Minutes,5000.0,200.636560,50.551309,0.0,166.375,201.00,234.10,363.70
Total Eve Calls,5000.0,100.191000,19.826496,0.0,87.000,100.00,114.00,170.00
Total Eve Charge,5000.0,17.054322,4.296843,0.0,14.140,17.09,19.90,30.91
Total Night Minutes,5000.0,200.391620,50.527789,0.0,166.900,200.40,234.70,395.00
Total Night Calls,5000.0,99.919200,19.958686,0.0,87.000,100.00,113.00,175.00
Total Night Charge,5000.0,9.017732,2.273763,0.0,7.510,9.02,10.56,17.77
Total International Minutes,5000.0,10.261780,2.761396,0.0,8.500,10.30,12.00,20.00
Total Intl Calls,5000.0,4.435200,2.456788,0.0,3.000,4.00,6.00,20.00
Total Intl Charge,5000.0,2.771196,0.745514,0.0,2.300,2.78,3.24,5.40
Number Customer Service calls,5000.0,1.570400,1.306363,0.0,1.000,1.00,2.00,9.00
Churn,5000.0,0.141400,0.348469,0.0,0.000,0.00,0.00,1.00
predictions,5000.0,0.136400,0.343247,0.0,0.000,0.00,0.00,1.00

In [22]:
telcochurn.head()

,State,Account Length,Area Code,Phone Number,International Plan,Voice mail Plan,Num of Voice mail Messages,Total Day Minutes,Total Day Calls,Total day Charge,...,Total Eve Charge,Total Night Minutes,Total Night Calls,Total Night Charge,Total International Minutes,Total Intl Calls,Total Intl Charge,Number Customer Service calls,Churn,predictions
0,KS,128,415,382-4657,0,1,25,265.1,110,45.07,...,16.78,244.7,91,11.01,10.0,3,2.70,1,0,0
1,OH,107,415,371-7191,0,1,26,161.6,123,27.47,...,16.62,254.4,103,11.45,13.7,3,3.70,1,0,0
2,NJ,137,415,358-1921,0,0,0,243.4,114,41.38,...,10.30,162.6,104,7.32,12.2,5,3.29,0,0,0
3,OH,84,408,375-9999,1,0,0,299.4,71,50.90,...,5.26,196.9,89,8.86,6.6,7,1.78,2,0,0
4,OK,75,415,330-6626,1,0,0,166.7,113,28.34,...,12.61,186.9,121,8.41,10.1,3,2.73,3,0,0

In [23]:
rfcm=metrics.confusion_matrix(telcochurn.Churn,telcochurn.predictions)

In [24]:
rfcm

array([[4292,    1],
       [  26,  681]], dtype=int64)

In [25]:
metrics.roc_curve(telcochurn.Churn, telcochurn.predictions)

(array([  0.00000000e+00,   2.32937340e-04,   1.00000000e+00]),
 array([ 0.        ,  0.96322489,  1.        ]),
 array([2, 1, 0], dtype=int64))

In [26]:
#### Logistic Regression
from sklearn.linear_model import LogisticRegression

In [27]:
logreg=LogisticRegression()

In [28]:
logregmodel = logreg.fit(telcochurn[features],telcochurn['Churn'])

In [29]:
logreg

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [30]:
telcochurn["LogRegPredict"]=logreg.predict(telcochurn[features])

In [31]:
telcochurn.head()

,State,Account Length,Area Code,Phone Number,International Plan,Voice mail Plan,Num of Voice mail Messages,Total Day Minutes,Total Day Calls,Total day Charge,...,Total Night Minutes,Total Night Calls,Total Night Charge,Total International Minutes,Total Intl Calls,Total Intl Charge,Number Customer Service calls,Churn,predictions,LogRegPredict
0,KS,128,415,382-4657,0,1,25,265.1,110,45.07,...,244.7,91,11.01,10.0,3,2.70,1,0,0,0
1,OH,107,415,371-7191,0,1,26,161.6,123,27.47,...,254.4,103,11.45,13.7,3,3.70,1,0,0,0
2,NJ,137,415,358-1921,0,0,0,243.4,114,41.38,...,162.6,104,7.32,12.2,5,3.29,0,0,0,0
3,OH,84,408,375-9999,1,0,0,299.4,71,50.90,...,196.9,89,8.86,6.6,7,1.78,2,0,0,1
4,OK,75,415,330-6626,1,0,0,166.7,113,28.34,...,186.9,121,8.41,10.1,3,2.73,3,0,0,0

In [32]:
logregCM=metrics.confusion_matrix(telcochurn.Churn,telcochurn.LogRegPredict)

In [33]:
logregCM

array([[4201,   92],
       [ 583,  124]], dtype=int64)

In [34]:
logreg.score(telcochurn[features],telcochurn['Churn'])

0.86499999999999999

In [36]:
####Decision Tree 
from sklearn.tree import DecisionTreeClassifier

In [37]:
dtclassifier = DecisionTreeClassifier()

In [39]:
dtcmodel = dtclassifier.fit(telcochurn[features],telcochurn['Churn'])

In [40]:
dtcmodel

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [41]:
telcochurn["DTCPredicts"]=dtcmodel.predict(telcochurn[features])

In [42]:
telcochurn.head()

,State,Account Length,Area Code,Phone Number,International Plan,Voice mail Plan,Num of Voice mail Messages,Total Day Minutes,Total Day Calls,Total day Charge,...,Total Night Calls,Total Night Charge,Total International Minutes,Total Intl Calls,Total Intl Charge,Number Customer Service calls,Churn,predictions,LogRegPredict,DTCPredicts
0,KS,128,415,382-4657,0,1,25,265.1,110,45.07,...,91,11.01,10.0,3,2.70,1,0,0,0,0
1,OH,107,415,371-7191,0,1,26,161.6,123,27.47,...,103,11.45,13.7,3,3.70,1,0,0,0,0
2,NJ,137,415,358-1921,0,0,0,243.4,114,41.38,...,104,7.32,12.2,5,3.29,0,0,0,0,0
3,OH,84,408,375-9999,1,0,0,299.4,71,50.90,...,89,8.86,6.6,7,1.78,2,0,0,1,0
4,OK,75,415,330-6626,1,0,0,166.7,113,28.34,...,121,8.41,10.1,3,2.73,3,0,0,0,0

In [45]:
dtc_cm=metrics.confusion_matrix(telcochurn.Churn,telcochurn.LogRegPredict)

In [46]:
dtcmodel.score(telcochurn[features],telcochurn['Churn'])

1.0

In [47]:
dtc_cm

array([[4201,   92],
       [ 583,  124]], dtype=int64)